<?php defined( 'ABSPATH' ) OR die( 'This script cannot be accessed directly.' );

// Get header layout
function n2mu_default_config( $param ) {

    $config = array(
        'logo-option'                       =>  '1',
        'logo-img'                          =>  get_template_directory_uri() . '/img/logo.png',
        'logo-img-sticky'                   =>  get_template_directory_uri() . '/img/logo.png',
        'logo-img-mobile'                   =>  get_template_directory_uri() . '/img/logo.png',
        'logo-img-height'                   =>  '28',
        'logo-text'                         =>  'Magnat',
        'page-preloader'                    =>  false,
        'header-layout'                     =>  'header1',
        'header-top-height'                 =>  '50',
        'header-middle-height'              =>  '100',
        'header-bottom-height'              =>  '50',
        'header-mobile-height'              =>  '75',
        'header-mobile-point'               =>  '1000',
        'header-tools-search'               =>  true,
        'header-tools-cart'                 =>  true,
        'header-sticky'                     =>  false,
        'footer-columns'                    =>  '0',
        'footer-top-borders'                =>  false,
        'footer-bottom-enabled'             =>  true,
        'copyrights'                        =>  '<a href="http://magnat.n2mu.studio" target="_blank">Magnat theme</a>',
        'color-main-theme'                  =>  '#33C6C6',
        'color-buttons'                     =>  '#33C6C6',
        'color-buttons-font'                =>  '#fff',
        'color-buttons-hover'               =>  '#33C6C6',
        'color-buttons-font-hover'          =>  '#efefef',
        'color-body'                        =>  '#72787b',
        'color-h1'                          =>  '#2b2b2b',
        'color-h2'                          =>  '#2b2b2b',
        'color-h3'                          =>  '#2b2b2b',
        'color-h4'                          =>  '#2b2b2b',
        'color-h5'                          =>  '#2b2b2b',
        'color-h6'                          =>  '#2b2b2b',
        'color-page-heading-title'          =>  '#2b2b2b',
        'color-page-heading-subtitle'       =>  '#2b2b2b',
        'color-link-regular'                =>  '#333',
        'color-link-hover'                  =>  '#33C6C6',
        'color-link-active'                 =>  '#33C6C6',
        'color-link-menu-top-regular'       =>  '#fff',
        'color-link-menu-top-hover'         =>  '#e6e6e6',
        'color-link-menu-top-active'        =>  '#e6e6e6',
        'color-link-menu-middle-regular'    =>  '#2b2b2b',
        'color-link-menu-middle-hover'      =>  '#33C6C6',
        'color-link-menu-middle-active'     =>  '#33C6C6',
        'color-link-menu-bottom-regular'    =>  '#fff',
        'color-link-menu-bottom-hover'      =>  '#e6e6e6',
        'color-link-menu-bottom-active'     =>  '#e6e6e6',
        'color-link-menu-submenu-regular'   =>  '#fff',
        'color-link-menu-submenu-hover'     =>  '#fff',
        'color-link-menu-submenu-active'    =>  '#fff',
        'color-menu-mobile-link'            =>  '#2b2b2b',
        'color-header-top-content'          =>  '#fff',
        'color-header-top'                  =>  '#33C6C6',
        'color-header-middle'               =>  '#fff',
        'color-header-bottom'               =>  '#33C6C6',
        'color-header-submenu-color'        =>  '#333',
        'color-header-submenu-alpha'        =>  '.95',
        'color-header-submenu-hover-color'  =>  '#33C6C6',
        'color-header-submenu-hover-alpha'  =>  '.99',
        'color-footer-top-headings'         =>  '#fff',
        'color-footer-top-text'             =>  '#d1d1d1',
        'color-footer-top-link-regular'     =>  '#d1d1d1',
        'color-footer-top-link-hover'       =>  '#33C6C6',
        'color-footer-top-link-active'      =>  '#33C6C6',
        'color-footer-top'                  =>  '#212121',
        'color-footer-top-border-color'     =>  '#333',
        'color-footer-top-border-alpha'     =>  '.20',
        'color-footer-bottom-headings'      =>  '#fff',
        'color-footer-bottom-text'          =>  '#d1d1d1',
        'color-footer-bottom-link-regular'  =>  '#d1d1d1',
        'color-footer-bottom-link-hover'    =>  '#33C6C6',
        'color-footer-bottom-link-active'   =>  '#33C6C6',
        'color-footer-bottom'               =>  '#111111',
        'color-element-portfolio-hover-color' =>  '#33C6C6',
        'color-element-portfolio-hover-alpha' =>  '.80',
        // Typography - TODO
        'page-heading-on'                   =>  true,
        'page-heading-style'                =>  'heading-centered',
        'page-heading-background'           =>  '#efefef',
        'page-heading-spacing-top'          =>  '70px',
        'page-heading-spacing-bottom'       =>  '70px',
        'page-padding-top'                  =>  '30px',
        'page-padding-bottom'               =>  '30px',
        'page-comments'                     =>  true,
        'blog-listing-style'                =>  'blog-listing-simple',
        'blog-listing-img'                  =>  'n2mu-cropped-big',
        'blog-listing-meta'                 =>  true,
        'blog-listing-meta-date'            =>  true,
        'blog-listing-meta-author'          =>  true,
        'blog-listing-meta-categories'      =>  true,
        'blog-listing-meta-comments'        =>  true,
        'blog-listing-meta-tags'            =>  true,
        'blog-single-meta'                  =>  true,
        'blog-single-meta-date'             =>  true,
        'blog-single-meta-author'           =>  true,
        'blog-single-meta-categories'       =>  true,
        'blog-single-meta-comments'         =>  true,
        'blog-single-meta-tags'             =>  true,
        'n2mu-blog-full-post-content'       =>  false,
        'portfolio-related'                 =>  false,
        'portfolio-page-slug'               =>  '',
        'layout'                            =>  '0',
        'layout-post'                       =>  '1',
        'layout-shop'                       =>  '0',
        'woo-catalog-mode'                  =>  false,
        'quick-translation'                 =>  false,
    );

    if (array_key_exists($param, $config)) {
        return $config[$param];
    } else {
        return '';
    }
    
    
}